// ---- Location & static reference data for McCormacks Beach analyst ----

export const LOCATION = {
  name: "McCormacks Beach",
  area: "Eastern Passage, Nova Scotia",
  // OSM "McCormacks Beach Provincial Park" node, so the marker lands exactly on the
  // beach as drawn on the OpenStreetMap tiles.
  lat: 44.60823,
  lon: -63.49233,
  tz: "America/Halifax",
  // Nearest CHS/IWLS tide gauge with predictions (Halifax - same harbour system,
  // ~7 km NW; Eastern Passage tides track it within a few minutes).
  tideStationId: "5cebf1df3d0f4a073c4bbcbb",
  tideStationName: "Halifax (CHS 00490)",
};

// Comparison sites used for "nearby activity" context.
export const NEARBY = [
  { name: "Fisherman's Cove", lat: 44.5907, lon: -63.4585, note: "Sheltered cove + wharf, baitfish staging" },
  { name: "Devils Island area", lat: 44.582, lon: -63.456, note: "Outer harbour island, strong current edges" },
  { name: "Lawrencetown", lat: 44.642, lon: -63.345, note: "Open coast surf, striper beat" },
  { name: "Halifax Harbour approaches", lat: 44.609, lon: -63.55, note: "Main shipping channel, deep water" },
];

export interface SpeciesDef {
  key: string;
  name: string;
  emoji: string;
  priority: number;
  months: number[]; // 1-12 months present/active from shore
  peakMonths: number[];
  waterTempIdeal: [number, number]; // °C sweet spot
  waterTempRange: [number, number]; // °C tolerable
  prefersMovingWater: number; // 0..1 weight toward strong tidal flow
  dawnDuskBias: number; // 0..1 how much low-light helps
  baseEncounter: number; // 0..100 baseline when in season
  eating: number; // 1..10
  rig: string;
  bait: string;
  size: string;
  location: string;
  notes: string;
  // NS retention guidance (general; always re-verify before keeping)
  legalFlag: "keep" | "release" | "check";
  legal: string;
}

// June reference month for "today" defaults; engine uses live month.
export const SPECIES: SpeciesDef[] = [
  {
    key: "mackerel",
    name: "Atlantic Mackerel",
    emoji: "🐟",
    priority: 1,
    months: [5, 6, 7, 8, 9, 10],
    peakMonths: [6, 7, 8, 9],
    waterTempIdeal: [11, 18],
    waterTempRange: [8, 21],
    prefersMovingWater: 0.7,
    dawnDuskBias: 0.8,
    baseEncounter: 70,
    eating: 8,
    rig: "Sabiki / mackerel tree (size 4-6) under a casting float, or a single shiny jig",
    bait: "Bare gold/silver sabikis; tip with squid strip. Cast metals: Kastmaster, Gibbs Minnow",
    size: "25-38 cm (0.2-0.6 kg)",
    location: "Boardwalk drop-off & island-facing point on moving water",
    notes: "Schools roam - once you find them it's fast. Watch for surface boils & diving birds.",
    legalFlag: "check",
    legal: "Recreational mackerel was under a federal closure recently - VERIFY current DFO status before keeping. If open, no licence/limit historically for personal use.",
  },
  {
    key: "herring",
    name: "Atlantic Herring",
    emoji: "🐟",
    priority: 2,
    months: [4, 5, 6, 9, 10, 11],
    peakMonths: [5, 6, 10],
    waterTempIdeal: [6, 12],
    waterTempRange: [3, 15],
    prefersMovingWater: 0.5,
    dawnDuskBias: 0.95,
    baseEncounter: 35,
    eating: 7,
    rig: "Small sabiki (size 8-10), fished slow & deep at dusk",
    bait: "Bare sabiki; tiny flash. No bait needed",
    size: "20-30 cm",
    location: "Boardwalk deeper water at dusk/dark, near mackerel schools",
    notes: "Mostly a low-light / after-dark catch. Often mixed in with mackerel sabiki sessions.",
    legalFlag: "keep",
    legal: "Open recreationally; sensible personal limits. Re-verify DFO bait-fishery notices.",
  },
  {
    key: "pollock",
    name: "Pollock",
    emoji: "🐟",
    priority: 3,
    months: [5, 6, 7, 8, 9, 10, 11],
    peakMonths: [6, 9, 10, 11],
    waterTempIdeal: [7, 14],
    waterTempRange: [4, 17],
    prefersMovingWater: 0.8,
    dawnDuskBias: 0.85,
    baseEncounter: 40,
    eating: 7,
    rig: "Jig (1-3 oz) or float + bait near rocks; metal jigs on the swing",
    bait: "Squid, mackerel strip, clam; lures: white/green jigs, soft plastics, metals",
    size: "30-55 cm (harbour pollock), occasional larger",
    location: "Rocky points & current seams around the island on strong tide",
    notes: "Aggressive on moving water near structure - best near the rocks at tide change.",
    legalFlag: "keep",
    legal: "Open recreationally; check minimum size/limits. Generally retainable.",
  },
  {
    key: "cod",
    name: "Atlantic Cod",
    emoji: "🐠",
    priority: 4,
    months: [10, 11, 12, 1, 2, 3, 4],
    peakMonths: [11, 12, 1],
    waterTempIdeal: [2, 9],
    waterTempRange: [0, 12],
    prefersMovingWater: 0.6,
    dawnDuskBias: 0.5,
    baseEncounter: 18,
    eating: 9,
    rig: "Heavy bottom rig / jig near deep structure",
    bait: "Clam, squid, mackerel; cod jigs",
    size: "40-70 cm+",
    location: "Deep drop-offs & channel edges, island side",
    notes: "Shore cod from the harbour is opportunistic and cold-season. Strictly regulated.",
    legalFlag: "check",
    legal: "Groundfish (cod) recreational season is SHORT & date-specific in the Maritimes - only keep during the announced open window and within tag/size limits. Otherwise RELEASE.",
  },
  {
    key: "haddock",
    name: "Haddock",
    emoji: "🐠",
    priority: 5,
    months: [11, 12, 1, 2, 3, 4],
    peakMonths: [12, 1, 2],
    waterTempIdeal: [2, 8],
    waterTempRange: [0, 11],
    prefersMovingWater: 0.6,
    dawnDuskBias: 0.4,
    baseEncounter: 8,
    eating: 9,
    rig: "Bottom rig with circle hooks, deep",
    bait: "Clam, squid",
    size: "40-60 cm",
    location: "Deep channel edges (rare from this shore)",
    notes: "Uncommon from shore here - primarily a boat fish. Bonus if it happens.",
    legalFlag: "check",
    legal: "Falls under the same groundfish recreational window as cod - VERIFY open season & limits, otherwise release.",
  },
  {
    key: "winter-flounder",
    name: "Winter Flounder",
    emoji: "🐡",
    priority: 6,
    months: [4, 5, 6, 7, 9, 10, 11],
    peakMonths: [5, 6, 10],
    waterTempIdeal: [4, 14],
    waterTempRange: [1, 18],
    prefersMovingWater: 0.2,
    dawnDuskBias: 0.3,
    baseEncounter: 30,
    eating: 8,
    rig: "Light bottom rig, two-hook, small (size 6-8) hooks on a sandy/mud bottom",
    bait: "Sea worms (bloodworm), clam, squid strips",
    size: "25-40 cm",
    location: "Sandy beach flats & boardwalk edge over soft bottom, near slack",
    notes: "Best fished still on the bottom around the slower water at the top/bottom of the tide.",
    legalFlag: "keep",
    legal: "Open recreationally; observe local size sense. Retainable.",
  },
  {
    key: "smooth-flounder",
    name: "Smooth Flounder",
    emoji: "🐡",
    priority: 7,
    months: [4, 5, 6, 7, 8, 9, 10],
    peakMonths: [5, 6, 9],
    waterTempIdeal: [6, 16],
    waterTempRange: [2, 20],
    prefersMovingWater: 0.2,
    dawnDuskBias: 0.3,
    baseEncounter: 18,
    eating: 7,
    rig: "Light bottom rig, very small hooks on mud/sand",
    bait: "Worm, clam, small bait strips",
    size: "15-30 cm",
    location: "Estuarine soft bottom near the beach & boardwalk",
    notes: "Small estuary flatfish; same tactics as winter flounder, lighter.",
    legalFlag: "keep",
    legal: "Open recreationally. Small - keep only worthwhile fish.",
  },
  {
    key: "striped-bass",
    name: "Striped Bass",
    emoji: "🐟",
    priority: 8,
    months: [5, 6, 7, 8, 9, 10],
    peakMonths: [6, 7, 9, 10],
    waterTempIdeal: [12, 20],
    waterTempRange: [8, 24],
    prefersMovingWater: 0.9,
    dawnDuskBias: 0.95,
    baseEncounter: 25,
    eating: 7,
    rig: "Medium spinning, single barbless hook; swimbaits / soft plastics / topwater",
    bait: "Live/cut mackerel; lures: paddletails, SP Minnow, topwater at dawn",
    size: "40-80 cm (slot-dependent)",
    location: "Current seams, rip lines off the point, dawn/dusk on moving water",
    notes: "Follows the mackerel/baitfish. Hard fight, great sight-fishing on calm dawns.",
    legalFlag: "check",
    legal: "Striped bass has a SLOT SIZE and season in NS (DFO Maritimes). BARBLESS hooks required. Verify open dates & slot before keeping; otherwise release carefully.",
  },
  {
    key: "cunner",
    name: "Cunner",
    emoji: "🐟",
    priority: 9,
    months: [5, 6, 7, 8, 9, 10],
    peakMonths: [6, 7, 8],
    waterTempIdeal: [10, 19],
    waterTempRange: [6, 22],
    prefersMovingWater: 0.3,
    dawnDuskBias: 0.2,
    baseEncounter: 60,
    eating: 5,
    rig: "Tiny hook bottom rig tight to the rocks",
    bait: "Worm, clam, mussel, squid scraps",
    size: "12-25 cm",
    location: "Rocky points & boardwalk pilings, right against structure",
    notes: "Always around the rocks - great for keeping kids busy, edible but bony/small.",
    legalFlag: "keep",
    legal: "No specific restriction typically; bait-stealer, keep larger ones for the pan.",
  },
  {
    key: "rainbow-smelt", name: "Rainbow Smelt", emoji: "🐟", priority: 10,
    months: [11, 12, 1, 2, 3], peakMonths: [12, 1, 2], waterTempIdeal: [0, 6], waterTempRange: [-1, 10],
    prefersMovingWater: 0.4, dawnDuskBias: 0.85, baseEncounter: 35, eating: 8,
    rig: "Tiny hooks (size 8-12) on a smelt rig, light line",
    bait: "Tiny worm/shrimp bits or bare gold hooks; small jigs",
    size: "12-20 cm", location: "Estuaries, wharves and bridges over deeper channels, after dark",
    notes: "Cold-season favourite, hook-fished or dipped at night through fall and winter.",
    legalFlag: "check", legal: "Smelt have seasons and gear rules (incl. dip-net seasons) - VERIFY DFO/NS before fishing.",
  },
  {
    key: "tomcod", name: "Atlantic Tomcod (Frostfish)", emoji: "🐠", priority: 11,
    months: [11, 12, 1, 2], peakMonths: [12, 1], waterTempIdeal: [0, 5], waterTempRange: [-1, 9],
    prefersMovingWater: 0.4, dawnDuskBias: 0.6, baseEncounter: 25, eating: 6,
    rig: "Light bottom rig, small hooks",
    bait: "Worm, clam, small bait bits",
    size: "15-30 cm", location: "Estuaries and harbour wharves in late fall and winter",
    notes: "A small cod relative that runs inshore in the cold - fun winter shore fishing.",
    legalFlag: "keep", legal: "Generally open for personal use; observe sensible limits. VERIFY.",
  },
  {
    key: "white-hake", name: "White Hake", emoji: "🐠", priority: 12,
    months: [6, 7, 8, 9, 10, 11], peakMonths: [9, 10, 11], waterTempIdeal: [5, 12], waterTempRange: [2, 16],
    prefersMovingWater: 0.5, dawnDuskBias: 0.75, baseEncounter: 18, eating: 8,
    rig: "Bottom rig or jig in deeper water",
    bait: "Squid, mackerel strip, clam",
    size: "40-70 cm", location: "Deep channel edges and harbour holes, often after dark",
    notes: "Soft-fleshed but excellent fresh; a night bottom-fishing bonus.",
    legalFlag: "check", legal: "Groundfish - check current recreational rules/closures before keeping.",
  },
  {
    key: "american-plaice", name: "American Plaice (Dab)", emoji: "🐡", priority: 13,
    months: [5, 6, 7, 9, 10], peakMonths: [6, 10], waterTempIdeal: [3, 10], waterTempRange: [0, 14],
    prefersMovingWater: 0.2, dawnDuskBias: 0.3, baseEncounter: 15, eating: 8,
    rig: "Light two-hook bottom rig, small hooks on sand/mud",
    bait: "Sea worms, clam, squid strip",
    size: "25-45 cm", location: "Sandy/muddy bottom in deeper water near channels",
    notes: "A flatfish often caught on flounder gear - superb eating.",
    legalFlag: "check", legal: "Falls under groundfish/flatfish rules - VERIFY size and season.",
  },
  {
    key: "sea-run-brook-trout", name: "Sea-run Brook Trout (Salter)", emoji: "🐟", priority: 14,
    months: [4, 5, 6, 9, 10], peakMonths: [5, 6, 9], waterTempIdeal: [6, 15], waterTempRange: [2, 19],
    prefersMovingWater: 0.6, dawnDuskBias: 0.95, baseEncounter: 20, eating: 9,
    rig: "Light spinning or fly; small spoons, spinners, flies",
    bait: "Worms, small spoons (Little Cleo), spinners, streamers",
    size: "20-40 cm", location: "Estuaries and river mouths on moving water at dawn/dusk",
    notes: "Brook trout that drop to salt to feed - prime in spring near river mouths.",
    legalFlag: "check", legal: "Trout season, limits and a licence apply even in estuaries - VERIFY NS Anglers' Handbook.",
  },
  {
    key: "spiny-dogfish", name: "Spiny Dogfish", emoji: "🦈", priority: 15,
    months: [6, 7, 8, 9, 10], peakMonths: [7, 8, 9], waterTempIdeal: [8, 16], waterTempRange: [5, 20],
    prefersMovingWater: 0.5, dawnDuskBias: 0.5, baseEncounter: 25, eating: 6,
    rig: "Heavy mono leader (abrasive skin), bottom rig or float",
    bait: "Mackerel, squid, any cut bait",
    size: "60-100 cm", location: "Deeper water off points and channels",
    notes: "A small shark - mind the dorsal spines. Good eating skinned (classic fish & chips).",
    legalFlag: "keep", legal: "Keepable; handle carefully (mild venom on the dorsal spines).",
  },
  {
    key: "winter-skate", name: "Winter Skate", emoji: "🐡", priority: 16,
    months: [5, 6, 7, 8, 9, 10, 11], peakMonths: [6, 9, 10], waterTempIdeal: [4, 14], waterTempRange: [1, 18],
    prefersMovingWater: 0.3, dawnDuskBias: 0.4, baseEncounter: 20, eating: 6,
    rig: "Bottom rig, larger hook",
    bait: "Clam, squid, cut fish",
    size: "50-90 cm wingspan", location: "Sandy/mud bottom, channels and flats",
    notes: "The wings are good eating (scallop-like). Handle tail and skin carefully.",
    legalFlag: "check", legal: "Some skate species are at-risk/protected - identify before keeping; VERIFY.",
  },
  {
    key: "sculpin", name: "Shorthorn Sculpin", emoji: "🐡", priority: 17,
    months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], peakMonths: [10, 11, 12, 1], waterTempIdeal: [2, 12], waterTempRange: [-1, 18],
    prefersMovingWater: 0.2, dawnDuskBias: 0.3, baseEncounter: 45, eating: 4,
    rig: "Bottom rig tight to structure",
    bait: "Worm, clam, cut bait",
    size: "15-35 cm", location: "Rocky bottom and harbour structure",
    notes: "A common spiny-headed bottom grabber - mostly a bait-stealer but edible.",
    legalFlag: "keep", legal: "No specific limit; handle the head spines carefully.",
  },
  {
    key: "gaspereau", name: "Gaspereau (Alewife)", emoji: "🐟", priority: 18,
    months: [4, 5, 6], peakMonths: [5], waterTempIdeal: [8, 16], waterTempRange: [4, 20],
    prefersMovingWater: 0.7, dawnDuskBias: 0.6, baseEncounter: 30, eating: 5,
    rig: "Small sabiki or a tiny weighted hook; small spoons",
    bait: "Bare small hooks with a little flash; small spoons",
    size: "25-30 cm", location: "River mouths and fishways during the spring run",
    notes: "Big spring spawning runs into rivers - bony but great smoked/pickled and superb bait.",
    legalFlag: "check", legal: "River-herring runs are regulated (some closures/licensed harvest) - VERIFY before keeping.",
  },
  {
    key: "american-shad", name: "American Shad", emoji: "🐟", priority: 19,
    months: [5, 6, 7], peakMonths: [6], waterTempIdeal: [12, 20], waterTempRange: [8, 24],
    prefersMovingWater: 0.7, dawnDuskBias: 0.7, baseEncounter: 12, eating: 6,
    rig: "Light spinning; shad darts, small spoons, tiny jigs",
    bait: "Shad darts, small flashy jigs and spoons",
    size: "40-60 cm", location: "Tidal rivers and estuaries (e.g. Shubenacadie/Fundy) on the run",
    notes: "Hard-fighting 'poor man's tarpon' - bony but the roe is prized.",
    legalFlag: "check", legal: "Regulated - VERIFY season/limits; often a catch-and-release focus.",
  },
  {
    key: "wolffish", name: "Atlantic Wolffish", emoji: "🐺", priority: 20,
    months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], peakMonths: [11, 12, 1], waterTempIdeal: [1, 8], waterTempRange: [-1, 12],
    prefersMovingWater: 0.3, dawnDuskBias: 0.4, baseEncounter: 4, eating: 8,
    rig: "Heavy bottom rig near rock",
    bait: "Clam, crab, whelk",
    size: "50-100 cm", location: "Rocky deep structure (rare from shore)",
    notes: "Powerful crushing jaws - uncommon inshore.",
    legalFlag: "release", legal: "RELEASE - Atlantic wolffish is protected under the Species at Risk Act. Do not retain.",
  },
  {
    key: "lumpfish", name: "Lumpfish", emoji: "🐡", priority: 21,
    months: [4, 5, 6], peakMonths: [5], waterTempIdeal: [2, 9], waterTempRange: [-1, 12],
    prefersMovingWater: 0.3, dawnDuskBias: 0.4, baseEncounter: 10, eating: 4,
    rig: "Bottom near rock and kelp",
    bait: "Worm, small cut bait",
    size: "20-45 cm", location: "Rocky, kelpy shoreline in spring (spawning)",
    notes: "Comes shallow to spawn in spring; the male guards the eggs - best released.",
    legalFlag: "release", legal: "Recommend RELEASE - a conservation concern, and the guarding male is vital to the nest.",
  },
];

// ---- Freshwater (lake/river) species for Nova Scotia ----
// NS inland fishing needs a provincial Recreational Fishing Licence and follows the
// NS Anglers' Handbook (seasons/limits vary by county & water). Always re-verify.
export const FRESH_SPECIES: SpeciesDef[] = [
  {
    key: "brook-trout",
    name: "Brook Trout (Speckled)",
    emoji: "🐟",
    priority: 1,
    months: [4, 5, 6, 9],
    peakMonths: [5, 6],
    waterTempIdeal: [8, 16],
    waterTempRange: [2, 20],
    prefersMovingWater: 0.5,
    dawnDuskBias: 0.9,
    baseEncounter: 55,
    eating: 9,
    rig: "Light spinning or fly; worm under a float, or small spinner/spoon",
    bait: "Worms, small spinners (Mepps/Panther Martin), spoons, trout flies",
    size: "20-35 cm",
    location: "Cool inflows, spring holes, drop-offs and shaded shoreline",
    notes: "Native NS favourite. Best early season and at dawn/dusk; seek cooler water in summer.",
    legalFlag: "check",
    legal: "Trout season is typically Apr 1 - Sep 30 (varies by county); daily limits apply. Licence required. VERIFY the NS Anglers' Handbook.",
  },
  {
    key: "smallmouth-bass",
    name: "Smallmouth Bass",
    emoji: "🐟",
    priority: 2,
    months: [5, 6, 7, 8, 9, 10],
    peakMonths: [6, 7, 9],
    waterTempIdeal: [16, 24],
    waterTempRange: [10, 28],
    prefersMovingWater: 0.3,
    dawnDuskBias: 0.7,
    baseEncounter: 60,
    eating: 6,
    rig: "Medium spinning; soft plastics, jigs, crankbaits, topwater",
    bait: "Senkos/tubes, crankbaits, spinnerbaits, live worms; topwater at dawn",
    size: "25-45 cm",
    location: "Rocky shoals, points, drop-offs and submerged structure",
    notes: "Hard-fighting and abundant in many NS lakes. Hold tight to rock and structure.",
    legalFlag: "keep",
    legal: "Open per NS bass regulations (often year-round, limits apply). Licence required. VERIFY local rules.",
  },
  {
    key: "chain-pickerel",
    name: "Chain Pickerel",
    emoji: "🐡",
    priority: 3,
    months: [4, 5, 6, 7, 8, 9, 10, 11],
    peakMonths: [5, 6, 9, 10],
    waterTempIdeal: [12, 22],
    waterTempRange: [4, 27],
    prefersMovingWater: 0.2,
    dawnDuskBias: 0.6,
    baseEncounter: 55,
    eating: 6,
    rig: "Medium spinning with a wire/heavy fluoro leader (sharp teeth)",
    bait: "Spinnerbaits, spoons, swimbaits, live minnows near weeds",
    size: "30-60 cm",
    location: "Weed edges, lily pads, bays and slow shallows",
    notes: "Aggressive ambush predator. Introduced/spreading - do NOT move live fish between waters.",
    legalFlag: "keep",
    legal: "Generally keepable; in many waters there is no limit on this introduced species. Never transport live. VERIFY.",
  },
  {
    key: "white-perch",
    name: "White Perch",
    emoji: "🐟",
    priority: 4,
    months: [4, 5, 6, 7, 8, 9, 10],
    peakMonths: [6, 7],
    waterTempIdeal: [14, 22],
    waterTempRange: [6, 26],
    prefersMovingWater: 0.2,
    dawnDuskBias: 0.7,
    baseEncounter: 65,
    eating: 7,
    rig: "Light spinning; small jigs, worm on a bottom/float rig",
    bait: "Worms, small jigs, tiny spinners; tip jigs with worm",
    size: "15-28 cm",
    location: "Drop-offs and open water near structure, often in schools",
    notes: "Schooling panfish - find one, find many. Excellent eating despite the size.",
    legalFlag: "keep",
    legal: "Open recreationally with a licence; generous limits. VERIFY.",
  },
  {
    key: "yellow-perch",
    name: "Yellow Perch",
    emoji: "🐟",
    priority: 5,
    months: [4, 5, 6, 7, 8, 9, 10, 11],
    peakMonths: [5, 6, 10],
    waterTempIdeal: [12, 20],
    waterTempRange: [4, 25],
    prefersMovingWater: 0.15,
    dawnDuskBias: 0.5,
    baseEncounter: 55,
    eating: 8,
    rig: "Light bottom/float rig with small hooks; small jigs",
    bait: "Worms, small minnows, small jigs",
    size: "15-25 cm",
    location: "Weed edges and soft-bottom flats near drop-offs",
    notes: "Day-active schooling panfish, superb on the plate.",
    legalFlag: "keep",
    legal: "Open recreationally with a licence; generous limits. VERIFY.",
  },
  {
    key: "brown-trout",
    name: "Brown Trout",
    emoji: "🐟",
    priority: 6,
    months: [4, 5, 6, 9, 10],
    peakMonths: [5, 9, 10],
    waterTempIdeal: [10, 17],
    waterTempRange: [3, 21],
    prefersMovingWater: 0.5,
    dawnDuskBias: 0.95,
    baseEncounter: 25,
    eating: 8,
    rig: "Spinning or fly; spinners, spoons, streamers",
    bait: "Spinners, spoons, worms, streamer flies",
    size: "25-45 cm",
    location: "Stocked lakes and river mouths; deeper cool water by day",
    notes: "Stocked in select NS waters. Low-light and overcast are prime; wary fish.",
    legalFlag: "check",
    legal: "Same trout season/limits as brook trout generally; licence required. VERIFY the NS Anglers' Handbook.",
  },
  {
    key: "american-eel",
    name: "American Eel",
    emoji: "🐍",
    priority: 7,
    months: [5, 6, 7, 8, 9, 10],
    peakMonths: [7, 8],
    waterTempIdeal: [15, 24],
    waterTempRange: [8, 28],
    prefersMovingWater: 0.4,
    dawnDuskBias: 1.0,
    baseEncounter: 30,
    eating: 7,
    rig: "Bottom rig, sturdy hook",
    bait: "Worms, cut bait, dead minnow on the bottom",
    size: "40-80 cm",
    location: "Soft-bottom holes, inflows/outflows, near dark",
    notes: "Strictly a night/after-dark catch. Slimy but very good smoked.",
    legalFlag: "check",
    legal: "Eel has size limits and a licence requirement; some closures exist. VERIFY before keeping.",
  },
  {
    key: "rainbow-trout", name: "Rainbow Trout", emoji: "🐟", priority: 8,
    months: [4, 5, 6, 9, 10], peakMonths: [5, 10], waterTempIdeal: [10, 18], waterTempRange: [4, 22],
    prefersMovingWater: 0.4, dawnDuskBias: 0.85, baseEncounter: 30, eating: 8,
    rig: "Light spinning or fly; spinners, spoons, bait under a float",
    bait: "Worms, PowerBait, spinners, spoons, flies",
    size: "25-40 cm", location: "Stocked lakes - cruise the shoreline and drop-offs",
    notes: "Stocked in select NS lakes; a hard fighter that takes lures and bait readily.",
    legalFlag: "check", legal: "Trout season, limits and a licence apply - VERIFY NS Anglers' Handbook.",
  },
  {
    key: "largemouth-bass", name: "Largemouth Bass", emoji: "🐟", priority: 9,
    months: [5, 6, 7, 8, 9, 10], peakMonths: [6, 7, 9], waterTempIdeal: [18, 26], waterTempRange: [12, 30],
    prefersMovingWater: 0.1, dawnDuskBias: 0.8, baseEncounter: 25, eating: 6,
    rig: "Medium spinning; weedless soft plastics, topwater",
    bait: "Senkos, jigs, frogs/topwater, spinnerbaits worked into cover",
    size: "30-50 cm", location: "Weedy bays, lily pads, docks and wood cover",
    notes: "Introduced to some NS waters; ambushes from heavy cover - great topwater fun.",
    legalFlag: "keep", legal: "Open per NS bass rules with a licence; never move live fish between waters. VERIFY.",
  },
  {
    key: "brown-bullhead", name: "Brown Bullhead (Catfish)", emoji: "🐡", priority: 10,
    months: [5, 6, 7, 8, 9], peakMonths: [6, 7, 8], waterTempIdeal: [16, 26], waterTempRange: [8, 30],
    prefersMovingWater: 0.1, dawnDuskBias: 1.0, baseEncounter: 40, eating: 7,
    rig: "Simple bottom rig, sturdy hook",
    bait: "Worms, cut bait or dough on the bottom after dark",
    size: "20-35 cm", location: "Soft-bottom shallows and bays, best after dark",
    notes: "Easy night fishing and firm, tasty fillets. Mind the pectoral spines.",
    legalFlag: "keep", legal: "Open with a licence; typically generous limits. VERIFY.",
  },
  {
    key: "white-sucker", name: "White Sucker", emoji: "🐟", priority: 11,
    months: [4, 5, 6, 7, 8, 9, 10], peakMonths: [5, 6], waterTempIdeal: [10, 20], waterTempRange: [4, 26],
    prefersMovingWater: 0.4, dawnDuskBias: 0.5, baseEncounter: 35, eating: 5,
    rig: "Light bottom rig, small hook",
    bait: "Worms on the bottom",
    size: "25-45 cm", location: "River pools and lake inflows over gravel and sand",
    notes: "Bottom feeder that spawns up tributaries in spring; bony but edible (good smoked).",
    legalFlag: "keep", legal: "Usually no specific limit, but an inland licence is still required. VERIFY.",
  },
  {
    key: "atlantic-salmon-fresh", name: "Atlantic Salmon", emoji: "🐟", priority: 12,
    months: [6, 7, 8, 9, 10], peakMonths: [9, 10], waterTempIdeal: [8, 16], waterTempRange: [3, 20],
    prefersMovingWater: 0.8, dawnDuskBias: 0.9, baseEncounter: 8, eating: 8,
    rig: "Fly gear (often fly-only water); barbless hooks",
    bait: "Flies only on most waters - VERIFY gear rules before fishing",
    size: "45-80 cm", location: "Salmon pools on flowing rivers (lake outlets for landlocked fish)",
    notes: "Iconic but heavily protected - most NS salmon angling is catch-and-release, fly-only, with many closures.",
    legalFlag: "release", legal: "RELEASE unless a specific river/season is open - needs a special licence/tags and many rivers are closed. VERIFY.",
  },
];

// Euryhaline / diadromous saltwater species that also run into brackish estuaries
// and tidal river mouths - the only "sea" fish you'd expect where fresh meets salt.
export const EURYHALINE_KEYS = new Set<string>([
  "striped-bass", "mackerel", "gaspereau", "american-shad", "rainbow-smelt", "sea-run-brook-trout", "winter-flounder",
]);

// ---- Notable Nova Scotia freshwater fishing lakes (starter set; add your own via the map) ----
// Lake centres + sizes from OpenStreetMap (Overpass). Regenerate via: node scripts/gen-lakes.mjs
export const NS_LAKES: { name: string; lat: number; lon: number; note: string; radiusKm: number; brackish?: boolean }[] = [
  { name: "Porters Lake", lat: 44.72542, lon: -63.33206, note: "Large tidal/estuarine lake; smallmouth/pickerel/perch up top, brackish & sea fish near the south outlet", radiusKm: 4, brackish: true },
  { name: "Lake Banook", lat: 44.67921, lon: -63.55626, note: "Dartmouth, smallmouth/perch; Shubenacadie Canal system", radiusKm: 0.8 },
  { name: "Lake Micmac", lat: 44.69229, lon: -63.55371, note: "Dartmouth, bass/perch; linked to Banook & Charles", radiusKm: 1.1 },
  { name: "Lake Charles", lat: 44.72321, lon: -63.55181, note: "Shubenacadie Canal chain, bass/pickerel", radiusKm: 1.7 },
  { name: "Long Lake", lat: 44.62334, lon: -63.64055, note: "Halifax/Spryfield reservoir, trout/bass, shore access", radiusKm: 1.7 },
  { name: "First Lake", lat: 44.77043, lon: -63.66105, note: "Lower Sackville, perch/bass/pickerel", radiusKm: 1.2 },
  { name: "Shubenacadie Grand Lake", lat: 44.90942, lon: -63.60049, note: "Major lake on the Shubenacadie system, boatable to Fundy; bass/perch/pickerel", radiusKm: 4 },
  { name: "Lake Echo", lat: 44.71993, lon: -63.37986, note: "Bass/pickerel/perch, east of Dartmouth", radiusKm: 2.3 },
  { name: "Williams Lake", lat: 44.61929, lon: -63.59688, note: "Halifax, trout/bass, quiet shore fishing", radiusKm: 0.8 },
];

// Boatable/fishable waterway links live in ./waterways.ts (geometry from OpenStreetMap).

// WMO weather code -> short label + emoji
export const WEATHER_CODES: Record<number, { label: string; icon: string }> = {
  0: { label: "Clear", icon: "☀️" },
  1: { label: "Mainly clear", icon: "🌤️" },
  2: { label: "Partly cloudy", icon: "⛅" },
  3: { label: "Overcast", icon: "☁️" },
  45: { label: "Fog", icon: "🌫️" },
  48: { label: "Rime fog", icon: "🌫️" },
  51: { label: "Light drizzle", icon: "🌦️" },
  53: { label: "Drizzle", icon: "🌦️" },
  55: { label: "Heavy drizzle", icon: "🌧️" },
  61: { label: "Light rain", icon: "🌧️" },
  63: { label: "Rain", icon: "🌧️" },
  65: { label: "Heavy rain", icon: "🌧️" },
  66: { label: "Freezing rain", icon: "🌧️" },
  71: { label: "Light snow", icon: "🌨️" },
  73: { label: "Snow", icon: "🌨️" },
  75: { label: "Heavy snow", icon: "❄️" },
  80: { label: "Rain showers", icon: "🌦️" },
  81: { label: "Showers", icon: "🌧️" },
  82: { label: "Violent showers", icon: "⛈️" },
  85: { label: "Snow showers", icon: "🌨️" },
  95: { label: "Thunderstorm", icon: "⛈️" },
  96: { label: "Thunderstorm + hail", icon: "⛈️" },
  99: { label: "Severe thunderstorm", icon: "⛈️" },
};

export function weatherLabel(code: number) {
  return WEATHER_CODES[code] ?? { label: "-", icon: "🌥️" };
}

export function compassDir(deg: number): string {
  const dirs = ["N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"];
  return dirs[Math.round(deg / 22.5) % 16];
}
